name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v10.24.1
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10.24.1
      - run: npm install
      - run: npm run bootstrap
      - run: npm run build
      - name: Upload lambda build
        uses: actions/upload-artifact@v2
        with:
          name: lambda-build
          path: lambda/build
      - name: Upload react server build
        uses: actions/upload-artifact@v2
        with:
          name: react-server-build
          path: react-app/server-build
      - name: Upload react client build
        uses: actions/upload-artifact@v2
        with:
          name: react-client-build
          path: react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v10.24.1
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10.24.1
      - run: npm install
      - run: npm run bootstrap
      - name: Download lambda build
        uses: actions/download-artifact@v2
        with:
          name: lambda-build
          path: lambda/build
      - name: Download react server build
        uses: actions/download-artifact@v2
        with:
          name: react-server-build
          path: react-app/server-build
      - name: Download react client build
        uses: actions/download-artifact@v2
        with:
          name: react-client-build
          path: react-app/build
      - run: echo ${GITHUB_REF}
      - name: Deploy
        run: npm run deploy
        env:
          SUFFIX: master
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
          API_ENDPOINT: ${{ format('master.{0}', secrets.API_HOSTED_ZONE_NAME) }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
