name: learn-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v10.12.0
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10.12.0
      - run: npm install

