name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v10.12.0
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10.12.0
      - run: npm install
      - run: npm run bootstrap
      - run: npm run build
      - name: Upload lambda build
        uses: actions/upload-artifact@v2
        with:
          name: lambda-build
          path: lambda/build
      - name: Upload react server build
        uses: actions/upload-artifact@v2
        with:
          name: react-server-build
          path: react-app/server-build
      - name: Upload react client build
        uses: actions/upload-artifact@v2
        with:
          name: react-client-build
          path: react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS v10.12.0
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10.12.0
      - run: npm install
      - run: npm run bootstrap
      - name: Download lambda build
        uses: actions/download-artifact@v2
        with:
          name: lambda-build
          path: lambda/build
      - name: Download react server build
        uses: actions/download-artifact@v2
        with:
          name: react-server-build
          path: react-app/server-build
      - name: Download react client build
        uses: actions/download-artifact@v2
        with:
          name: react-client-build
          path: react-app/build
      - name: Deploy
        run: npm run deploy
        env:
          STACK_NAME: master



